output_path: ${oc.env:OUTPUT_PATH}
dataset_path: ${oc.env:DATASET_PATH}
metadata_file: "metadata.csv"
speaker_embeddings_file: ${paths.dataset_path}/speakers.pth
emotion_embeddings_file: ${paths.dataset_path}/emotions.pth
speaker_encoder_model_dir: ${paths.output_path}/speaker_encoder
pretrained_checkpoint_dir: ${paths.output_path}/pretrained_yourtts_cml
restore_path: ${paths.pretrained_checkpoint_dir}/checkpoints_yourtts_cml_tts_dataset/best_model.pth
local_tar_path: /mnt/sagemaker-nvme/checkpoints_yourtts_cml_tts_dataset.tar.bz 