# Main configuration file that holds all default settings.
# These can be overridden by specific experiment files.

paths:
  # The following paths are now loaded from your .env file
  # output_path: "..."
  # dataset_path: "..."
  metadata_file: 'metadata.csv'
  speaker_embeddings_file: ${paths.dataset_path}/speakers.pth
  emotion_embeddings_file: ${paths.dataset_path}/emotions.pth
  speaker_encoder_model_dir: ${paths.output_path}/speaker_encoder
  pretrained_checkpoint_dir: ${paths.output_path}/pretrained_yourtts_cml
  restore_path: ${paths.pretrained_checkpoint_dir}/checkpoints_yourtts_cml_tts_dataset/best_model.pth
  local_tar_path: /mnt/sagemaker-nvme/checkpoints_yourtts_cml_tts_dataset.tar.bz

audio:
  sample_rate: 24000
  max_audio_len_seconds: 15

training:
  batch_size: 12
  eval_batch_size: 6
  num_loader_workers: 8
  epochs: 500
  learning_rate: 0.00001 # 1e-5
  save_step: 5000
  max_text_len: 200
  skip_train_epoch: false
  use_pretrained_lang_embeddings: true

s3:
  # bucket_name is loaded from your .env file
  checkpoint_prefix_yourtts: 'tts/yourtts/yourtts-multilingual-checkpoints-finetuned'
  checkpoint_prefix_vecl: 'tts/vecl/vecl-multilingual-checkpoints-finetuned'
  cml_tts_checkpoint_key: 'tts/cml-tts/checkpoints_yourtts_cml_tts_dataset.tar.bz'

wandb:
  use_wandb: true
  project_yourtts: 'yourtts-finetuned'
  project_vecl: 'vecl-finetuned'
  # entity is loaded from your .env file

model:
  type: 'vecl'
  use_emotion_consistency_loss: true 